// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="convbas_convbas,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=4650,HLS_SYN_LUT=5060,HLS_VERSION=2025_1}" *)

module convbas (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] in_r;
wire   [63:0] out_r;
wire   [31:0] H;
wire   [31:0] W;
wire   [63:0] w_kernel;
reg    gmem2_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [31:0] W_read_reg_382;
reg   [31:0] H_read_reg_389;
reg   [63:0] out_r_read_reg_395;
reg   [63:0] in_r_read_reg_400;
reg   [62:0] trunc_ln_reg_405;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [15:0] local_kernel_load_reg_431;
wire    ap_CS_fsm_state14;
wire   [31:0] sub17_fu_293_p2;
reg   [31:0] sub17_reg_446;
wire   [31:0] sub51_fu_298_p2;
reg   [31:0] sub51_reg_451;
reg   [15:0] local_kernel_load_1_reg_456;
reg   [15:0] local_kernel_load_2_reg_461;
wire   [30:0] empty_33_fu_329_p3;
reg   [30:0] empty_33_reg_466;
wire   [31:0] select_ln31_fu_358_p3;
reg   [31:0] select_ln31_reg_471;
wire   [31:0] select_ln31_1_fu_366_p3;
reg   [31:0] select_ln31_1_reg_476;
wire    ap_CS_fsm_state15;
reg   [15:0] local_kernel_load_3_reg_491;
reg   [15:0] local_kernel_load_4_reg_496;
wire    ap_CS_fsm_state16;
reg   [15:0] local_kernel_load_5_reg_521;
reg   [15:0] local_kernel_load_6_reg_526;
wire   [63:0] grp_fu_264_p2;
reg   [63:0] bound8_reg_531;
reg   [15:0] local_kernel_load_7_reg_536;
wire    ap_CS_fsm_state17;
reg   [15:0] local_kernel_load_8_reg_541;
reg   [3:0] local_kernel_address0;
reg    local_kernel_ce0;
reg    local_kernel_we0;
wire   [15:0] local_kernel_q0;
wire   [15:0] local_kernel_q1;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_done;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_idle;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_ready;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWVALID;
wire   [63:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWADDR;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWID;
wire   [31:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWLEN;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWSIZE;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWBURST;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWLOCK;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWCACHE;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWPROT;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWQOS;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWREGION;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WVALID;
wire   [15:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WDATA;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WSTRB;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WLAST;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WID;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARVALID;
wire   [63:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARADDR;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARID;
wire   [31:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARLEN;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARSIZE;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARBURST;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARLOCK;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARCACHE;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARPROT;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARQOS;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARREGION;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_RREADY;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_BREADY;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_address0;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_ce0;
wire    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_we0;
wire   [15:0] grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_d0;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_done;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_idle;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_ready;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWID;
wire   [31:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WVALID;
wire   [15:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WDATA;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WSTRB;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WID;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARID;
wire   [31:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_RREADY;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_BREADY;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWID;
wire   [31:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WVALID;
wire   [15:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WDATA;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WSTRB;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WID;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARID;
wire   [31:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARUSER;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_RREADY;
wire    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_BREADY;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
reg    gmem0_0_ARVALID;
wire    gmem0_0_ARREADY;
wire    gmem0_0_RVALID;
reg    gmem0_0_RREADY;
wire   [15:0] gmem0_0_RDATA;
wire   [9:0] gmem0_0_RFIFONUM;
wire    gmem0_0_BVALID;
reg    gmem1_0_AWVALID;
wire    gmem1_0_AWREADY;
reg    gmem1_0_WVALID;
wire    gmem1_0_WREADY;
wire    gmem1_0_ARREADY;
wire    gmem1_0_RVALID;
wire   [15:0] gmem1_0_RDATA;
wire   [9:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
reg    gmem1_0_BREADY;
wire    gmem2_0_AWREADY;
wire    gmem2_0_WREADY;
reg    gmem2_0_ARVALID;
wire    gmem2_0_ARREADY;
reg   [63:0] gmem2_0_ARADDR;
reg   [31:0] gmem2_0_ARLEN;
wire    gmem2_0_RVALID;
reg    gmem2_0_RREADY;
wire   [15:0] gmem2_0_RDATA;
wire   [9:0] gmem2_0_RFIFONUM;
wire    gmem2_0_BVALID;
reg    grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start_reg;
wire    ap_CS_fsm_state18;
wire  signed [63:0] sext_ln23_fu_278_p1;
reg    local_kernel_ce0_local;
reg   [3:0] local_kernel_address0_local;
reg    local_kernel_ce1_local;
reg   [3:0] local_kernel_address1_local;
wire   [31:0] grp_fu_264_p0;
wire   [31:0] grp_fu_264_p1;
wire   [30:0] tmp_fu_303_p4;
wire   [30:0] trunc_ln31_fu_319_p1;
wire   [0:0] icmp_fu_313_p2;
wire   [30:0] add_ln31_fu_323_p2;
wire   [31:0] sub_fu_288_p2;
wire   [30:0] tmp_1_fu_337_p4;
wire   [0:0] icmp26_fu_347_p2;
wire   [31:0] add_ln31_1_fu_353_p2;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire   [63:0] grp_fu_264_p00;
wire   [63:0] grp_fu_264_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start_reg = 1'b0;
#0 grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start_reg = 1'b0;
end

convbas_local_kernel_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
local_kernel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(local_kernel_address0),
    .ce0(local_kernel_ce0),
    .we0(local_kernel_we0),
    .d0(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_d0),
    .q0(local_kernel_q0),
    .address1(local_kernel_address1_local),
    .ce1(local_kernel_ce1_local),
    .q1(local_kernel_q1)
);

convbas_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2 grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start),
    .ap_done(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_done),
    .ap_idle(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_idle),
    .ap_ready(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_ready),
    .m_axi_gmem2_0_AWVALID(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(1'b0),
    .m_axi_gmem2_0_RID(1'd0),
    .m_axi_gmem2_0_RFIFONUM(gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(1'd0),
    .m_axi_gmem2_0_RRESP(2'd0),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .sext_ln23(trunc_ln_reg_405),
    .local_kernel_address0(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_address0),
    .local_kernel_ce0(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_ce0),
    .local_kernel_we0(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_we0),
    .local_kernel_d0(grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_d0)
);

convbas_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4 grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start),
    .ap_done(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_done),
    .ap_idle(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_idle),
    .ap_ready(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .m_axi_gmem1_0_AWVALID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(gmem1_0_AWREADY),
    .m_axi_gmem1_0_AWADDR(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(gmem1_0_WREADY),
    .m_axi_gmem1_0_WDATA(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(1'b0),
    .m_axi_gmem1_0_ARADDR(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(1'b0),
    .m_axi_gmem1_0_RREADY(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(16'd0),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(10'd0),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(gmem1_0_BVALID),
    .m_axi_gmem1_0_BREADY(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .sub17(sub17_reg_446),
    .bound8(bound8_reg_531),
    .W_cast(W_read_reg_382),
    .in_r(in_r_read_reg_400),
    .local_kernel_load_7(local_kernel_load_7_reg_536),
    .local_kernel_load_8(local_kernel_load_8_reg_541),
    .local_kernel_load_1(local_kernel_load_1_reg_456),
    .local_kernel_load(local_kernel_load_reg_431),
    .local_kernel_load_2(local_kernel_load_2_reg_461),
    .local_kernel_load_3(local_kernel_load_3_reg_491),
    .local_kernel_load_4(local_kernel_load_4_reg_496),
    .local_kernel_load_5(local_kernel_load_5_reg_521),
    .local_kernel_load_6(local_kernel_load_6_reg_526),
    .p_cast(empty_33_reg_466),
    .sub51_cast(sub51_reg_451),
    .out_r(out_r_read_reg_395)
);

convbas_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_r(in_r),
    .out_r(out_r),
    .H(H),
    .W(W),
    .w_kernel(w_kernel),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

convbas_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARADDR),
    .I_CH0_ARLEN(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(16'd0),
    .I_CH0_WSTRB(2'd0),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

convbas_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(gmem1_0_AWVALID),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWADDR),
    .I_CH0_AWLEN(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWLEN),
    .I_CH0_WVALID(gmem1_0_WVALID),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WDATA),
    .I_CH0_WSTRB(grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WSTRB),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(gmem1_0_BREADY)
);

convbas_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem2_0_ARVALID),
    .I_CH0_ARREADY(gmem2_0_ARREADY),
    .I_CH0_ARADDR(gmem2_0_ARADDR),
    .I_CH0_ARLEN(gmem2_0_ARLEN),
    .I_CH0_RVALID(gmem2_0_RVALID),
    .I_CH0_RREADY(gmem2_0_RREADY),
    .I_CH0_RDATA(gmem2_0_RDATA),
    .I_CH0_RFIFONUM(gmem2_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem2_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem2_0_WREADY),
    .I_CH0_WDATA(16'd0),
    .I_CH0_WSTRB(2'd0),
    .I_CH0_BVALID(gmem2_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

convbas_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U35(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_264_p0),
    .din1(grp_fu_264_p1),
    .ce(1'b1),
    .dout(grp_fu_264_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start_reg <= 1'b1;
        end else if ((grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_ready == 1'b1)) begin
            grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start_reg <= 1'b1;
        end else if ((grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_ready == 1'b1)) begin
            grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        H_read_reg_389 <= H;
        W_read_reg_382 <= W;
        in_r_read_reg_400 <= in_r;
        out_r_read_reg_395 <= out_r;
        trunc_ln_reg_405 <= {{w_kernel[63:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        bound8_reg_531 <= grp_fu_264_p2;
        local_kernel_load_5_reg_521 <= local_kernel_q0;
        local_kernel_load_6_reg_526 <= local_kernel_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        empty_33_reg_466 <= empty_33_fu_329_p3;
        local_kernel_load_1_reg_456 <= local_kernel_q1;
        local_kernel_load_2_reg_461 <= local_kernel_q0;
        select_ln31_1_reg_476 <= select_ln31_1_fu_366_p3;
        select_ln31_reg_471 <= select_ln31_fu_358_p3;
        sub17_reg_446 <= sub17_fu_293_p2;
        sub51_reg_451 <= sub51_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        local_kernel_load_3_reg_491 <= local_kernel_q0;
        local_kernel_load_4_reg_496 <= local_kernel_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        local_kernel_load_7_reg_536 <= local_kernel_q0;
        local_kernel_load_8_reg_541 <= local_kernel_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        local_kernel_load_reg_431 <= local_kernel_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem2_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        gmem0_0_ARVALID = grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_ARVALID;
    end else begin
        gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        gmem0_0_RREADY = grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem0_0_RREADY;
    end else begin
        gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        gmem1_0_AWVALID = grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_AWVALID;
    end else begin
        gmem1_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        gmem1_0_BREADY = grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_BREADY;
    end else begin
        gmem1_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17))) begin
        gmem1_0_WVALID = grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_m_axi_gmem1_0_WVALID;
    end else begin
        gmem1_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem2_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem2_0_ARADDR = sext_ln23_fu_278_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem2_0_ARADDR = grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARADDR;
    end else begin
        gmem2_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem2_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem2_0_ARLEN = 64'd9;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem2_0_ARLEN = grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARLEN;
    end else begin
        gmem2_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem2_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem2_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem2_0_ARVALID = grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_ARVALID;
    end else begin
        gmem2_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem2_0_RREADY = grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_m_axi_gmem2_0_RREADY;
    end else begin
        gmem2_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem2_blk_n_AR = m_axi_gmem2_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        local_kernel_address0 = grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_address0;
    end else begin
        local_kernel_address0 = local_kernel_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        local_kernel_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        local_kernel_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        local_kernel_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        local_kernel_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        local_kernel_address0_local = 64'd0;
    end else begin
        local_kernel_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        local_kernel_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        local_kernel_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        local_kernel_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        local_kernel_address1_local = 64'd1;
    end else begin
        local_kernel_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        local_kernel_ce0 = grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_ce0;
    end else begin
        local_kernel_ce0 = local_kernel_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        local_kernel_ce0_local = 1'b1;
    end else begin
        local_kernel_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        local_kernel_ce1_local = 1'b1;
    end else begin
        local_kernel_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        local_kernel_we0 = grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_local_kernel_we0;
    end else begin
        local_kernel_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem2_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_1_fu_353_p2 = ($signed(H_read_reg_389) + $signed(32'd4294967294));

assign add_ln31_fu_323_p2 = ($signed(trunc_ln31_fu_319_p1) + $signed(31'd2147483647));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_33_fu_329_p3 = ((icmp_fu_313_p2[0:0] == 1'b1) ? add_ln31_fu_323_p2 : 31'd0);

assign grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start = grp_convbas_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2_fu_230_ap_start_reg;

assign grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start = grp_convbas_Pipeline_VITIS_LOOP_31_3_VITIS_LOOP_32_4_fu_238_ap_start_reg;

assign grp_fu_264_p0 = grp_fu_264_p00;

assign grp_fu_264_p00 = select_ln31_reg_471;

assign grp_fu_264_p1 = grp_fu_264_p10;

assign grp_fu_264_p10 = select_ln31_1_reg_476;

assign icmp26_fu_347_p2 = (($signed(tmp_1_fu_337_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_fu_313_p2 = (($signed(tmp_fu_303_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign select_ln31_1_fu_366_p3 = ((icmp_fu_313_p2[0:0] == 1'b1) ? sub51_fu_298_p2 : 32'd0);

assign select_ln31_fu_358_p3 = ((icmp26_fu_347_p2[0:0] == 1'b1) ? add_ln31_1_fu_353_p2 : 32'd0);

assign sext_ln23_fu_278_p1 = $signed(trunc_ln_reg_405);

assign sub17_fu_293_p2 = ($signed(W_read_reg_382) + $signed(32'd4294967295));

assign sub51_fu_298_p2 = ($signed(W_read_reg_382) + $signed(32'd4294967294));

assign sub_fu_288_p2 = ($signed(H_read_reg_389) + $signed(32'd4294967295));

assign tmp_1_fu_337_p4 = {{sub_fu_288_p2[31:1]}};

assign tmp_fu_303_p4 = {{sub17_fu_293_p2[31:1]}};

assign trunc_ln31_fu_319_p1 = sub17_fu_293_p2[30:0];

endmodule //convbas
